name: QA Workflow

on:
  workflow_dispatch:
  pull_request:
    # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  QAFlow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen gcovr lcov cppcheck graphviz clang-format
          version: 1.0

      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: actions/setup-arm-toolchain@v1
        with:
          gcc-version: '13.3.rel1' # Especificar la versi√≥n deseada del compilador

      - name: Run style check
        uses: ./.github/actions/style

      - name: Run documentation check
        uses: ./.github/actions/document

      - name: Build project
        uses: ./.github/actions/build

